---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.10

suites:
  - name: default
    run_list:
      - recipe[interview-buster::mysql]
      - recipe[interview-buster::httpd]
      - recipe[interview-buster::python-webapp]
attributes:
