name 'interview-buster'
maintainer 'Dan Stark'
maintainer_email 'dstark75@gmail.com'
license 'MIT'
description 'Installs/Configures interview-buster'
long_description 'A LAMP virtual machine with tags that are intentionally broken'
version '0.1.1'
depends 'mysql'
