CREATE DATABASE IF NOT EXISTS pizza_toppings CHARACTER SET = UTF8;
USE pizza_toppings;
CREATE TABLE IF NOT EXISTS veggies (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(20),
on_pizza TINYINT(1)
);
CREATE TABLE IF NOT EXISTS meats (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(20),
on_pizza TINYINT(1)
);